POST http://localhost:8080/newFinalEvent
Content-Type: application/json

{
  "event": {
    "latitude": 50.0049,
    "longitude": 14.002504
  },
  "sensors": [
    {
      "lat": 50,
      "lon": 14.002504
    },
    {
      "lat": 50.01,
      "lon": 14.0025
    },
    {
      "lat": 50,
      "lon": 14
    }
  ]
}


###
POST http://localhost:8080/newFinalEvent
Content-Type: application/json

{
  "event": {
    "latitude": 50.10338,
    "longitude": 14.38991,
    "timestamp": "2021-02-01 15:00:35"
  },
  "sensors": [
    {
      "lat": 50.103082,
      "lon": 14.391701
    },
    {
      "lat": 50.104194,
      "lon": 14.394366
    },
    {
      "lat": 50.104012,
      "lon": 14.388319
    }
  ]
}


###
POST http://localhost:8080/newEvent
Content-Type: application/json

{
  "report": [
    {
      "id": 12,
      "time": 6698
    },
    {
      "id": 10,
      "time": 6698
    },
    {
      "id": 11,
      "time": 6698
    }
  ]
}

